name: challange_1

on:
  push:
    branches:
      3_challenge-1

jobs:
  job_1:
    name: Ubuntu job
    runs-on: ubuntu-latest
    steps:
      - name: Preparation
        uses: actions/checkout@v2
      - name: Date print-out
        run: date

  job_2:
    name: Windows job
    runs-on: windows-latest
    steps:
      - name: Preparation
        uses: actions/checkout@v2
      - name: Date print-out
        run: |
          "@echo off"
          "For /f 'tokens=2-4 delims=/ ' %%a in ('date /t') do (set mydate=%%c-%%a-%%b)"
          "For /f 'tokens=1-2 delims=/:' %%a in ('time /t') do (set mytime=%%a%%b)"
          "echo %mydate%_%mytime%"

  job_3:
    name: Mac job
    runs-on: macos-latest
    steps:
      - name: Preparation
        uses: actions/checkout@v2
      - name: Date print-out
        run: date

  job_4:
    name: Mac job
    runs-on: macos-latest
    needs: [job_1, job_2, job_3]
    steps:
      - name: Preparation
        uses: actions/checkout@v2
      - name: Date print-out
        run: date


